[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "api-$version"
version_scheme = "semver"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true

[tool.commitizen.customize]
changelog_pattern = "^(feat|fix)\\(api\\)(!)?:"