name: ML Pipeline
on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: "treediculous-grp"
  AZURE_WORKSPACE: "treediculous-ml-grp"
  AZURE_LOCATION: "northeurope"
  PYTHON_VERSION: "3.10.15"

permissions:
  contents: write
  packages: write

jobs:
  ml-pipeline:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    environment: treediculous

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      working-directory: model
      run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Install Azure CLI ML extension
      run: az extension add --name ml

    - name: setup azure
      working-directory: model/pipeline
      run: ./setup_azureml.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }}

    - name: Run pipeline
      working-directory: model/pipeline
      run: ./run_azureml.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }}