on:
  push:
    tags:
      - "web-*"

env:
  DOCKER_REGISTRY: "ghcr.io"

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  build-push-web-docker-image:
    runs-on: ubuntu-latest
    environment: treediculous
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Push docker image
        uses: docker/build-push-action@v6
        with:
          context: webapp
          file: webapp/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/patacoing/treediculous:${{ github.ref_name }}

  get-api-version:
    runs-on: ubuntu-latest
    environment: treediculous
    outputs:
      api-version: ${{ steps.get-api-version.outputs.api-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Get api version
        id: get-api-version
        run: echo "api-version=$(git describe --tags --match='api-*' HEAD --abbrev=0)" >> $GITHUB_OUTPUT

  deploy-web:
    uses: ./.github/workflows/deployment.yml
    needs:
      - build-push-web-docker-image
      - get-api-version
    with:
      api-version: ${{ needs.get-api-version.outputs.api-version }}
      web-version: ${{ github.ref_name }}
      working-directory: deployment
      deploy-api: false
    secrets: inherit